### ISSUE TITLE
Create the API endpoint

### ISSUE THREAD

**Issue by adityadahake** [adityadahake/send-email-api#3]
- Create the API endpoint: "/send-email" .
- Use "nodemailer" npm package to implement the email sending function.

**Comment by Abhi-Dev12** [comment]
In routes Email.js
const controller = require("../controllers/EmailController");
but in controller file name is not updated

in the index.js all the require statements are put together at the top

**Comment by adityadahake** [comment]
Just create a new issue as Bugfix/.. and raise a PR.
